# -*- coding: utf-8 -*-
# Generated by Django 5.2.7 on 2025-10-12 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 10, 12, 12, 55, 41, 860298, tzinfo=datetime.timezone.utc
                ),
                verbose_name="가입일",
            ),
            preserve_default=False,
        ),
    ]
