# .github/workflows/checks.yml

name: Code Quality & Tests

on:
  push:
    branches:
      - main # main 브랜치에 PUSH 될 때 실행
  pull_request: # PR 요청 시 실행

jobs:
  ci:
    runs-on: ubuntu-latest # GitHub Actions 환경

    # PostgreSQL 서비스 정의
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432 # localhost:5432로 연결
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries