# .github/workflows/checks.yml

name: Code Quality & Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    # 1. uv 설치
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH # uv 실행 파일만 PATH에 추가

    # 2. uv를 사용해 의존성 설치 (ruff 포함)
    - name: Install Dependencies
      run: uv sync

    # 3. ruff 실행은 python -m 사용 (No module named ruff 오류 해결)
    - name: Run Ruff (Linting & Formatting Check)
      run: python -m ruff check .

    - name: Run Django Migration & Tests
      env:
        DATABASE_URL: postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}
      run: |
        python manage.py migrate --no-input
        python manage.py test